/// Flutter icons SampleApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SampleApp
///      fonts:
///       - asset: fonts/SampleApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: dangling_library_doc_comments

import "package:flutter/widgets.dart";

class BaseFlutterIcon {
  BaseFlutterIcon._();

  static const String _kFontFam = "SampleApp";
  // static const String? _kFontPkg = null;

  static const IconData contactInput = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData accountBox = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData accountCircle = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData apps = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData diamond = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData accountBalanceBaseFlutter =
      IconData(0xf008, fontFamily: _kFontFam);
  static const IconData bank = IconData(0xf19c, fontFamily: _kFontFam);
  static const IconData cubes = IconData(0xf1b3, fontFamily: _kFontFam);
  static const IconData connectDevelop =
      IconData(0xf20e, fontFamily: _kFontFam);
  static const IconData baseFlutter = IconData(0xf555, fontFamily: _kFontFam);
}
