// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_open_source_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2sDO-tzcfzlWlM2uL6TwHBAt9wlb6F0',
    appId: '1:845206888977:android:09ec98b662d78ce86487b0',
    messagingSenderId: '845206888977',
    projectId: 'chill-sim',
    storageBucket: 'chill-sim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6d_5rRvN59etYnfO9ERLsFwwUNGd1FMY',
    appId: '1:845206888977:ios:793eb908e3a195256487b0',
    messagingSenderId: '845206888977',
    projectId: 'chill-sim',
    storageBucket: 'chill-sim.firebasestorage.app',
    androidClientId: '845206888977-009i378dtfqiqntcjnp6ek6tdv4bkpvd.apps.googleusercontent.com',
    iosClientId: '845206888977-l726soo28mam56qq1s72oi3clqs4abh6.apps.googleusercontent.com',
    iosBundleId: 'zaheen.esim.chillsim',
  );

}